name: brew test-bot
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  test-bot:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Install Homebrew on Linux
        if: runner.os == 'Linux'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew shellenv >> "$GITHUB_ENV"

      - name: Run brew test-bot
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_ENV_HINTS: 1
        run: |
          brew test-bot --skip-setup \
            --tap=kaoh/globalplatform \
            kaoh/globalplatform/globalplatform
            ls -1
      - name: Save bootle
        uses: actions/upload-artifact@v4
        with:
          name: bottle-${{ matrix.os }}
          path: |
            ./globalplatform*.bottle.*
