name: brew test-bot
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  test-bot:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Run brew test-bot
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_ENV_HINTS: 1
        run: |
          brew test-bot --skip-setup \
            --tap=kaoh/globalplatform \
            kaoh/globalplatform/globalplatform
            ls -1
      - name: Save bootle
        uses: actions/upload-artifact@v4
        with:
          name: bottle-${{ matrix.os }}
          path: |
            ./globalplatform*.bottle.*
