name: brew test-bot
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  test-bot:
    runs-on: macos-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Run brew test-bot
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_ENV_HINTS: 1
        run: |
          brew test-bot --skip-setup \
            --tap=kaoh/globalplatform \
            kaoh/globalplatform/globalplatform
            ls -1
      - name: Save bootle
        uses: actions/upload-artifact@v4
        with:
          name: bottle-mac
          path: |
            ./globalplatform*.bottle.*
